import React from 'react';
import { Thermometer, Zap, Car, Plane, Utensils, Home } from 'lucide-react';

const AboutPage = () => {
  const categories = [
    {
      icon: Car,
      title: 'Transportation',
      description: 'Vehicle emissions from daily commuting and travel',
      impact: '29% of global emissions'
    },
    {
      icon: Zap,
      title: 'Energy',
      description: 'Electricity consumption from homes and workplaces',
      impact: '25% of global emissions'
    },
    {
      icon: Plane,
      title: 'Aviation',
      description: 'Flight travel for business and leisure',
      impact: '2.5% of global emissions'
    },
    {
      icon: Utensils,
      title: 'Diet',
      description: 'Food production and consumption patterns',
      impact: '24% of global emissions'
    },
    {
      icon: Home,
      title: 'Housing',
      description: 'Home heating, cooling, and maintenance',
      impact: '18% of global emissions'
    }
  ];

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-blue-50 via-emerald-50 to-green-50 py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-gray-900 mb-6">
              Understanding Your
              <span className="text-emerald-600 block">Carbon Footprint</span>
            </h1>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              Learn about carbon footprints, why they matter, and how our calculator 
              helps you make informed decisions for a sustainable future.
            </p>
          </div>
        </div>
      </section>

      {/* What is Carbon Footprint */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="lg:grid lg:grid-cols-2 lg:gap-16 items-center">
            <div>
              <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-6">
                What is a Carbon Footprint?
              </h2>
              <p className="text-lg text-gray-600 mb-6">
                A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) 
                that are generated by our actions. It's measured in equivalent tons of CO₂ per year.
              </p>
              <p className="text-lg text-gray-600 mb-6">
                Every activity in our daily lives contributes to our carbon footprint - from the electricity 
                we use to power our homes, to the food we eat, the transportation we use, and the products we buy.
              </p>
              <div className="bg-emerald-50 border-l-4 border-emerald-500 p-6 rounded">
                <div className="flex items-center mb-2">
                  <Thermometer className="h-6 w-6 text-emerald-600 mr-2" />
                  <h3 className="text-lg font-semibold text-gray-900">Did You Know?</h3>
                </div>
                <p className="text-gray-700">
                  The average global carbon footprint per person is about 4 tons CO₂ per year. 
                  However, to limit global warming to 1.5°C, we need to reduce this to 2.3 tons by 2030.
                </p>
              </div>
            </div>
            <div className="mt-12 lg:mt-0">
              <div className="bg-gradient-to-br from-emerald-100 to-green-100 p-8 rounded-2xl">
                <div className="text-center">
                  <div className="text-5xl font-bold text-emerald-600 mb-2">4.8T</div>
                  <p className="text-gray-700 mb-4">Global Average CO₂ per person/year</p>
                  <div className="text-3xl font-bold text-orange-500 mb-2">2.3T</div>
                  <p className="text-gray-700">Target for 2030 (Paris Agreement)</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Categories Section */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              Major Sources of Carbon Emissions
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Understanding the main contributors to your carbon footprint helps 
              identify the most impactful areas for reduction.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {categories.map((category, index) => (
              <div
                key={index}
                className="bg-white p-6 rounded-xl shadow-md hover:shadow-lg transform hover:-translate-y-1 transition-all duration-300"
              >
                <div className="bg-emerald-100 w-16 h-16 rounded-full flex items-center justify-center mb-4">
                  <category.icon className="h-8 w-8 text-emerald-600" />
                </div>
                <h3 className="text-xl font-semibold text-gray-900 mb-2">
                  {category.title}
                </h3>
                <p className="text-gray-600 mb-4">
                  {category.description}
                </p>
                <div className="bg-emerald-50 px-3 py-1 rounded-full inline-block">
                  <span className="text-sm font-medium text-emerald-700">
                    {category.impact}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How Our Calculator Works */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              How Our Calculator Works
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Our calculator uses scientifically verified emission factors from leading 
              climate research organizations to provide accurate results.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div>
              <div className="space-y-6">
                <div className="flex items-start space-x-4">
                  <div className="bg-emerald-500 text-white w-8 h-8 rounded-full flex items-center justify-center font-semibold text-sm">
                    1
                  </div>
                  <div>
                    <h3 className="text-lg font-semibold text-gray-900 mb-2">Input Your Data</h3>
                    <p className="text-gray-600">
                      Enter information about your lifestyle including transportation, 
                      energy use, travel, diet, and other activities.
                    </p>
                  </div>
                </div>
                <div className="flex items-start space-x-4">
                  <div className="bg-emerald-500 text-white w-8 h-8 rounded-full flex items-center justify-center font-semibold text-sm">
                    2
                  </div>
                  <div>
                    <h3 className="text-lg font-semibold text-gray-900 mb-2">Scientific Calculation</h3>
                    <p className="text-gray-600">
                      We multiply your inputs by verified emission factors from climate 
                      science research to calculate accurate CO₂ equivalent emissions.
                    </p>
                  </div>
                </div>
                <div className="flex items-start space-x-4">
                  <div className="bg-emerald-500 text-white w-8 h-8 rounded-full flex items-center justify-center font-semibold text-sm">
                    3
                  </div>
                  <div>
                    <h3 className="text-lg font-semibold text-gray-900 mb-2">Get Insights</h3>
                    <p className="text-gray-600">
                      Receive your total footprint, detailed breakdown by category, 
                      and personalized recommendations for reduction.
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div className="bg-gradient-to-br from-emerald-50 to-green-50 p-8 rounded-2xl">
              <h3 className="text-xl font-semibold text-gray-900 mb-6 text-center">
                Emission Factors We Use
              </h3>
              <div className="space-y-4">
                <div className="flex justify-between items-center">
                  <span className="text-gray-700">Petrol Car</span>
                  <span className="font-semibold text-emerald-600">0.271 kg CO₂/km</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-gray-700">Electricity (Grid)</span>
                  <span className="font-semibold text-emerald-600">0.233 kg CO₂/kWh</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-gray-700">Long-haul Flight</span>
                  <span className="font-semibold text-emerald-600">600 kg CO₂/flight</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-gray-700">Meat-heavy Diet</span>
                  <span className="font-semibold text-emerald-600">3.3 t CO₂/year</span>
                </div>
              </div>
              <p className="text-sm text-gray-600 mt-4 text-center">
                Based on IPCC and EPA data
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Why It Matters */}
      <section className="py-20 bg-gradient-to-r from-blue-600 to-emerald-600 text-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl md:text-4xl font-bold mb-6">
            Why Measuring Matters
          </h2>
          <p className="text-xl opacity-90 mb-8 max-w-3xl mx-auto">
            You can't manage what you don't measure. Understanding your carbon footprint 
            is the first step toward meaningful climate action.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mt-12">
            <div>
              <div className="text-3xl font-bold mb-2">🎯</div>
              <h3 className="text-xl font-semibold mb-2">Set Goals</h3>
              <p className="opacity-90">Establish baseline measurements to set realistic reduction targets</p>
            </div>
            <div>
              <div className="text-3xl font-bold mb-2">📊</div>
              <h3 className="text-xl font-semibold mb-2">Track Progress</h3>
              <p className="opacity-90">Monitor improvements over time and celebrate achievements</p>
            </div>
            <div>
              <div className="text-3xl font-bold mb-2">🌱</div>
              <h3 className="text-xl font-semibold mb-2">Take Action</h3>
              <p className="opacity-90">Make informed decisions about lifestyle changes that matter most</p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default AboutPage;